# Generated by Django 3.0.3 on 2020-03-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('url', models.URLField(default='https://github.com')),
                ('date_created', models.DateField()),
                ('date_updated', models.DateField()),
            ],
        ),
    ]
