# Generated by Django 3.0.3 on 2020-03-07 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200307_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='title',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='view',
            old_name='title',
            new_name='post',
        ),
    ]
